name: Semantic Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build: 
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ ubuntu-latest }}
    strategy:
      matrix:
        node: [ 14.17 ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
  
      - name: Install Dependencies
        uses: npm install

      - name: Build App
        run: npm run build

      - name: Semantic Relase
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
